development:
  sessions:
    default:
      database: pac
      hosts:
        - localhost

test:
  sessions:
    default:
      uri: pac_test

production:
  sessions:
    default:
      uri: pac_production
